### ISSUE TITLE
Auto-capitalization triggers inside comments

### ISSUE THREAD

**Issue by alfonsoss** [tmatijevich/language-as-structured-text#3]
Hello,

I've been testing the package lately with some Automation Studio projects. The Auto-capitalization is triggering for normal English words inside comments, so this creates unnecessary changes in the code. This needs then to be discarded in Git before committing, which creates extra work, or if there were no intentional changes in the code, close the file and click "don't save" (best case, but still extra annoyance. Sometimes, this triggers even from a simple "Search in all files", while previewing the file. I don't know if it's possible to add a setting to disable this functionality, or make it so it ignores comments.

**Comment by tmatijevich** [comment]
Thanks for the feedback.
There's now a setting for this in the latest commit. Clone or download and test it out, I will publish later.
The auto completion of uppercased keywords shouldn't occur in comments. If you have a specific example of this, would you mind sharing it?
